[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/voxell-tech/fynix"

[workspace.dependencies]
# fynix
fynix = { version = "0.0.1", path = "crates/fynix", default-features = false }
fynix_macros = { version = "0.0.1", path = "crates/fynix_macros" }
bevy_fynix = { version = "0.0.1", path = "crates/bevy_fynix", default-features = false }

# motiongfx
motiongfx_interp = { version = "0.3.0", default-features = false }

# bevy
bevy_app = { version = "0.19", default-features = false }
bevy_ecs = { version = "0.19", default-features = false }
bevy_picking = { version = "0.19", default-features = false }
bevy_time = { version = "0.19", default-features = false }
bevy_ui = { version = "0.19", default-features = false }

# other
lenz = { version = "0.1.0", default-features = false }
typarena = { version = "0.1.2", features = ["send", "sync"] }
hashbrown = { version = "0.17", default-features = false }

[workspace.lints.clippy]
redundant_type_annotations = "warn"
