[workspace]
members = ["crates/*", "examples/*"]
exclude = ["vendor/"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/voxell-tech/fynix"

[workspace.dependencies]
fynix = { version = "0.1.0", path = "crates/fynix", default-features = false }
fynix_macros = { version = "0.1.0", path = "crates/fynix_macros" }
fynix_elements = { version = "0.1.0", path = "crates/fynix_elements", default-features = false }
fynix_hit_test = { version = "0.1.0", path = "crates/fynix_hit_test", default-features = false }
typarena = { version = "0.1.0", path = "crates/typarena" }

rectree = { git = "https://github.com/voxell-tech/rectree", rev = "e9729bf" }
spatree = { git = "https://github.com/voxell-tech/spatree", rev = "61a3dab", default-features = false }
field_path = "0.4.1"
parley = { version = "0.7.0", default-features = false }
imaging = { version = "0.0.1", default-features = false }
imaging_vello = { version = "0.0.1", default-features = false, features = ["vello-0-8"] }

sparse_map = "0.3.0"
indexmap = { version = "2.14", default-features = false }
vello = "0.8.0"
winit = "0.30"
pollster = "0.4.0"
hashbrown = "0.16.1"
