[package]
name = "bevy_fynix"
description = "Bevy backend for fynix."
keywords = ["fynix", "bevy", "ui", "reactive", "plugin"]
categories = ["gui", "game-development"]
readme = "./README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# fynix
fynix = { workspace = true }

# bevy
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_picking = { workspace = true }
bevy_time = { workspace = true }
bevy_ui = { workspace = true }

[features]
default = ["std"]
std = ["fynix/std"]

[dev-dependencies]
bevy = { version = "0.19", default-features = false, features = [
    "2d",
    "bevy_ui",
    "bevy_ui_render",
    "ui_picking",
] }

[lints]
workspace = true
