use core::any::TypeId;
use core::mem;

pub use fynix_macros::fynix;
use hashbrown::HashMap;

use crate::element::{Element, ElementId, Elements};
use crate::events::Events;

/// User-written interaction handler: reacts to interaction `I` on an
/// element of type `E`, emitting messages into [`Events`].
pub type HandlerFn<E, I> = fn(&mut E, I, &mut Events);

/// Monomorphized dispatch for interaction type `I`, with the element
/// type `E` erased into the function pointer.
type DispatchFn<I> =
    fn(&mut Elements, &ElementId, I, &mut Events, *const ());

/// Recovers the typed handler and element, then runs the handler.
///
/// One of these is monomorphized per `(E, I)` and stored,
/// type-erased, inside a [`Dispatcher`].
fn dispatch_typed<E: Element, I>(
    elements: &mut Elements,
    id: &ElementId,
    interaction: I,
    events: &mut Events,
    handler: *const (),
) {
    // SAFETY: `Dispatcher::new` pairs `dispatch_typed::<E, I>` with a
    // `HandlerFn<E, I>` erased to `*const ()`, so the pointer is
    // exactly that handler.
    let handler = unsafe {
        mem::transmute::<*const (), HandlerFn<E, I>>(handler)
    };
    if let Some(element) = elements.get_typed_mut::<E>(id) {
        handler(element, interaction, events);
    }
}

/// A handler paired with the [`dispatch_typed`] that knows how to
/// call it. The interaction type `I` is retained; the element type is
/// erased into `dispatch`.
struct Dispatcher<I> {
    handler: *const (),
    dispatch: DispatchFn<I>,
}

impl<I> Dispatcher<I> {
    fn new<E: Element>(handler: HandlerFn<E, I>) -> Self {
        Self {
            handler: handler as *const (),
            dispatch: dispatch_typed::<E, I>,
        }
    }

    /// Erases the interaction type so dispatchers of every `I` share
    /// one map.
    fn untyped(self) -> UntypedDispatcher {
        UntypedDispatcher {
            handler: self.handler,
            dispatch: self.dispatch as *const (),
        }
    }

    fn run(
        self,
        elements: &mut Elements,
        id: &ElementId,
        interaction: I,
        events: &mut Events,
    ) {
        (self.dispatch)(
            elements,
            id,
            interaction,
            events,
            self.handler,
        );
    }
}

/// A [`Dispatcher`] with its interaction type erased, recovered via
/// [`Self::typed`] using the `I` known at dispatch.
#[derive(Clone, Copy)]
struct UntypedDispatcher {
    handler: *const (),
    dispatch: *const (),
}

impl UntypedDispatcher {
    fn typed<I>(self) -> Dispatcher<I> {
        // SAFETY: stored under a key whose `interaction_id` is
        // `TypeId::of::<I>()`, so `dispatch` is a `DispatchFn<I>`.
        let dispatch = unsafe {
            mem::transmute::<*const (), DispatchFn<I>>(self.dispatch)
        };
        Dispatcher {
            handler: self.handler,
            dispatch,
        }
    }
}

/// Identifies the handler for an `(element, interaction)` type pair.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InteractionKey {
    /// [`TypeId`] of the element type.
    pub element_id: TypeId,
    /// [`TypeId`] of the interaction type.
    pub interaction_id: TypeId,
}

impl InteractionKey {
    /// Builds a key for element type `E` reacting to interaction `I`.
    pub fn of<E: 'static, I: 'static>() -> Self {
        Self {
            element_id: TypeId::of::<E>(),
            interaction_id: TypeId::of::<I>(),
        }
    }
}

/// A registrar collected by [`inventory`] from every
/// `#[fynix(interaction)]` annotation.
///
/// Carries a registrar rather than a handler directly, so each
/// submission inserts its handler into the registry when it is built.
pub struct InteractionRegistrar {
    /// Inserts the handler into [`Interactions`].
    pub register: fn(&mut Interactions),
}

inventory::collect!(InteractionRegistrar);

/// Runtime index of interaction handlers, keyed by element and
/// interaction type.
///
/// One handler per `(element, interaction)` pair.
pub struct Interactions {
    dispatchers: HashMap<InteractionKey, UntypedDispatcher>,
}

impl Interactions {
    /// Builds the index from every [`InteractionRegistrar`] submitted
    /// through [`inventory`].
    pub fn new() -> Self {
        let mut interactions = Self {
            dispatchers: HashMap::new(),
        };
        for registrar in inventory::iter::<InteractionRegistrar> {
            (registrar.register)(&mut interactions);
        }
        interactions
    }

    /// Registers `handler` for element type `E` reacting to
    /// interaction `I`.
    ///
    /// Called by the registrars generated by `#[fynix(interaction)]`.
    pub fn register<E: Element, I: 'static>(
        &mut self,
        handler: HandlerFn<E, I>,
    ) {
        self.dispatchers.insert(
            InteractionKey::of::<E, I>(),
            Dispatcher::new(handler).untyped(),
        );
    }

    /// Dispatches `interaction` to the handler registered for `id`'s
    /// element type and `I`, if one exists.
    ///
    /// Returns `true` if a handler ran.
    pub fn dispatch<I: 'static>(
        &self,
        elements: &mut Elements,
        id: &ElementId,
        interaction: I,
        events: &mut Events,
    ) -> bool {
        let Some(element_id) = elements.type_id_of(id) else {
            return false;
        };
        let key = InteractionKey {
            element_id,
            interaction_id: TypeId::of::<I>(),
        };
        let Some(dispatcher) =
            self.dispatchers.get(&key).map(|d| d.typed::<I>())
        else {
            return false;
        };

        dispatcher.run(elements, id, interaction, events);
        true
    }
}

impl Default for Interactions {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use rectree::{Constraint, Size};

    use super::*;
    use crate::Fynix;
    use crate::element::layout::ElementNodes;
    use crate::element::{Element, ElementBuild};
    use crate::init::Init;

    #[derive(Init, Element)]
    struct Counter {
        count: u32,
    }

    impl ElementBuild for Counter {
        fn build(
            &self,
            _id: &ElementId,
            constraint: Constraint,
            _nodes: &mut ElementNodes,
        ) -> Size {
            constraint.min
        }
    }

    struct Click;

    #[derive(Debug, PartialEq)]
    struct Clicked(u32);

    #[fynix(interaction)]
    fn on_click_counter(
        counter: &mut Counter,
        _click: Click,
        events: &mut Events,
    ) {
        counter.count += 1;
        events.push(Clicked(counter.count));
    }

    #[test]
    fn dispatch_runs_registered_handler() {
        let mut world = ();
        let mut fynix = Fynix::new();
        let id = {
            let mut ctx = fynix.root_ctx(&mut world);
            ctx.add::<Counter>()
        };

        let interactions = Interactions::new();
        let ran = interactions.dispatch(
            &mut fynix.elements,
            &id,
            Click,
            &mut fynix.events,
        );

        assert!(ran);
        let counter =
            fynix.elements.get_typed::<Counter>(&id).unwrap();
        assert_eq!(counter.count, 1);
        assert_eq!(
            fynix.events.iter::<Clicked>().next(),
            Some(&Clicked(1))
        );
    }

    #[test]
    fn dispatch_without_handler_returns_false() {
        let mut world = ();
        let mut fynix = Fynix::new();
        let id = {
            let mut ctx = fynix.root_ctx(&mut world);
            ctx.add::<Counter>()
        };

        struct Hover;
        let interactions = Interactions::new();
        let ran = interactions.dispatch(
            &mut fynix.elements,
            &id,
            Hover,
            &mut fynix.events,
        );

        assert!(!ran);
    }
}
